# Generated by Django 4.2.5 on 2023-10-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_category_project_description_project_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='portfolio/static/assets/imgs'),
        ),
    ]
