# Generated by Django 4.2.5 on 2023-10-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='portfolio/images'),
        ),
    ]
